/**
 * Build the OpenCode adapter into a single self-contained file:
 *   dist/opencode-plugin.js
 *
 * OpenCode plugins are single files copied into ~/.config/opencode/plugins/,
 * so we bundle core + adapter with esbuild (external: none — Node builtins
 * and @opencode-ai/plugin are available at runtime in OpenCode).
 */
import { build } from "esbuild"
import { mkdirSync } from "node:fs"

mkdirSync("dist", { recursive: true })

await build({
  entryPoints: ["src/hooks/opencode.ts"],
  outfile: "dist/opencode-plugin.js",
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  external: ["@opencode-ai/plugin"],
  banner: {
    js: "// Generated by npm run build — see src/ for sources. Do not edit directly.",
  },
  logLevel: "info",
})

// Keep the pi adapter importable as plain TS sources; also emit a copy of core
// next to the bundle for hosts that load directories rather than single files.
await build({
  entryPoints: ["src/hooks/pi.ts"],
  outfile: "dist/pi-extension/index.ts",
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  external: ["@earendil-works/pi-coding-agent", "@sinclair/typebox"],
  banner: {
    js: "// Generated by npm run build — see src/ for sources. Do not edit directly.",
  },
  logLevel: "info",
})
